SELECT 
    START_TIME,
    END_TIME,
    WAREHOUSE_NAME,
    AVG_RUNNING,
    AVG_QUEUED_LOAD,
    AVG_QUEUED_PROVISIONING
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_LOAD_HISTORY
WHERE START_TIME > %(start_time)s
ORDER BY START_TIME ASC
LIMIT 1000;
