-- POV-4 Database Schema DDL
-- These tables are created in the database and schema configured in the environment variables.

CREATE TABLE IF NOT EXISTS POV4_PERFORMANCE_FINDINGS (
    FINDING_ID VARCHAR(36) PRIMARY KEY,
    TIMESTAMP TIMESTAMP_TZ NOT NULL,
    QUERY_ID VARCHAR(256) NOT NULL,
    WAREHOUSE VARCHAR(256) NOT NULL,
    OVERALL_SEVERITY VARCHAR(50) NOT NULL,
    EVIDENCE_QUALITY VARCHAR(50) NOT NULL,
    ISSUES VARIANT NOT NULL,
    METRICS VARIANT NOT NULL,
    ANALYSIS VARIANT
);

CREATE TABLE IF NOT EXISTS POV4_WATERMARKS (
    SOURCE_NAME VARCHAR(256) PRIMARY KEY,
    LAST_PROCESSED_TIMESTAMP TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS POV4_DLQ (
    ALERT_ID VARCHAR(36) PRIMARY KEY,
    FINDING_REFERENCE VARCHAR(36) NOT NULL,
    DESTINATION VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    DELIVERY_TIMESTAMP TIMESTAMP_TZ
);
