SELECT 
    START_TIME,
    END_TIME,
    SERVICE_TYPE,
    NAME as WAREHOUSE_NAME,
    CREDITS_USED_COMPUTE
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
WHERE START_TIME > %(start_time)s
ORDER BY START_TIME ASC
LIMIT 1000;
