SELECT 
    QUERY_ID,
    WAREHOUSE_NAME,
    START_TIME,
    END_TIME,
    CREDITS_ATTRIBUTED_COMPUTE
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY
WHERE START_TIME > %(start_time)s
ORDER BY START_TIME ASC
LIMIT 1000;
